const express = require("express")
const validation=require("../middlewares/validate.middleware")
const AsyncCatch=require("../utils/AsyncCatch")
const signUp=require("../validation/signup.Schema")
const login=require("../validation/login.Schema")
const forgotPassword=require("../validation/forgetPassword.schema")
const router = express.Router()
const authController = require("../controllers/auth.controller")
router.post("/signup",validation(signUp), AsyncCatch(authController.signUp))
router.post("/login", validation(login),AsyncCatch(authController.login))
router.post("/forgot-password",validation(forgotPassword),AsyncCatch(authController.forgotPassword))
module.exports = router
